# Generated by Django 6.0.1 on 2026-01-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_emailverification_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'Evro'), ('RUB', 'Rubl')], max_length=3, unique=True, verbose_name='Valyuta kodi')),
                ('rate_to_uzs', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="1 valyuta = ? so'm")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Valyuta kursi',
                'verbose_name_plural': 'Valyuta kurslari',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar'), ('EUR', 'Evro'), ('RUB', 'Rubl')], default='UZS', max_length=3, verbose_name='Valyuta'),
        ),
    ]
